service: hammy

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: production
  region: us-east-1

package:
  exclude:
    - src/**

functions:
  hammy:
    handler: dist/handler.handler
    events:
      - alexaSkill
